.TH voidpop "1" "October 2026" "voidpop version 1.1" "User Commands"
.SH NAME
voidpop \- dummy pop3 server
.SH SYNOPSIS
voidpop [\-h] [\-\-port PORT] [\-\-verbose] [\-\-version]
.SH DESCRIPTION
Dummy POP3 server that accepts any login and never has any messages.
.SS Options
.TP
\fB\-h\fR, \fB\-\-help\fR
show this help message and exit
.TP
\fB\-\-port\fR <PORT>
Listen on <PORT>
.TP
\fB\-\-verbose\fR
Log debug messages
.TP
\fB\-\-version\fR
show the version and exit
.SH FILES
.TP
\fC/etc/default/voidpop\fR
.SH ENVIRONMENT
Using an environment variable to set the port has the same effect as using
the \fI\-\-port\fP option.

.IP "VOIDPOP_PORT <port>"
Set the port to listen on.
